### ISSUE TITLE
Something wrong with typings

### ISSUE THREAD

**Issue by mudlee** [alexdrel/i18n-react#10]
Hi.

I got this message after install and compile:
`error TS2656: Exported external package typings file 'MY_PATH/node_modules/i18n-react/dist/i18n-react.ext.d.ts' is not a module. Please contact the package author to update the package definition.`

**Comment by mayheadd** [comment]
Hi I am also facing the same issue. **Exported external package typings file '/Users/WONINDIA/PANARAY-web/node_modules/i18n-react/dist/i18n-react.ext.d.ts' is not a module. Please contact the package author to update the package definition.** 

I checked the package.json file. There is no typings key in there. Please help.

**Comment by alexdrel** [comment]
I just published on npm version ```0.3.0-ts1``` which does not include TS2.0 typings. Of course once the new typescript version is considered stable I recommend upgrading to it and moving back to regular version of the package.
