### ISSUE TITLE
Key with a .

### ISSUE THREAD

**Issue by TakanashiOuken** [alexdrel/i18n-react#11]
Seems like if the key in the json contains a "." 
Then it never matches.

**Comment by alexdrel** [comment]
Yes, '.' is used for getting deep into JSON dictionary:
```json
"a": { "b": { "c": "MyText" }}}
```
``` <T.span text="a.b.c" />``` will be ```MyText```.

**Comment by TakanashiOuken** [comment]
Is there anyway I can escape it?

**Comment by alexdrel** [comment]
Unfortunately no.
