### ISSUE TITLE
TypeError: Can't add property context, object is not extensible

### ISSUE THREAD

**Issue by TakanashiOuken** [alexdrel/i18n-react#12]
React@0.13.3 is giving me an error, but React@0.14.8 is alright.

Warning: Component(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.
Warning: Don't set the props property of the React element. Instead, specify the correct value when initially creating the element.
/Users/timothywang/wsj/tmp/react-wsj-navigator/node_modules/react/lib/ReactCompositeComponent.js:153
    inst.context = publicContext;
                 ^

TypeError: Can't add property context, object is not extensible

**Comment by alexdrel** [comment]
Current version is not compatible with React 0.13. The older release may be
used.

**Comment by TakanashiOuken** [comment]
The oldest one I tried is 0.2.0. Doesn't work too.

**Comment by alexdrel** [comment]
0.1 had worked for sure.

**Comment by TakanashiOuken** [comment]
0.1.0 Gives me another error :(

Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
Warning: Only functions or strings can be mounted as React components.
/Users/timothywang/wsj/fp/react-wsj-navigator/node_modules/react/lib/ReactDefaultInjection.js:53
    tagName: type.toUpperCase(),
                 ^

TypeError: Cannot read property 'toUpperCase' of undefined
