### ISSUE TITLE
Getting a list's translation

### ISSUE THREAD

**Issue by Unforgiven-wanda** [alexdrel/i18n-react#15]
Hello,
I have a YAML file containing the following list:
```
fruits:
    - Apple
    - Orange
    - Strawberry
    - Mango
```

using `T.translate("fruits")` I would like to receive the translation of all my fruits, however all I get is the first one, Apple.
How to get all my items at once? Or at least iterate through them?

Thank you.

**Comment by alexdrel** [comment]
Sorry for the very late reply.
This scenario is not supported - ```translate``` returns a string or a React component that could be rendered and list was not considered as one. Although on second thought it can. 
You still can access the JSON/YAML object directly after it is loaded:
 ```
let dict = require('./texts.yml');
T.setTexts(dict);
let fruits = dict.fruits;
```
