### ISSUE TITLE
How do you handle multiple lang files.

### ISSUE THREAD

**Issue by piyaa** [alexdrel/i18n-react#18]
I have to render the json files based on the lang selected by user.
```
`import PropTypes from "react";
 var T = require('i18n-react').default;

export default (LanguageComp: constructor) => {
  class Language extends LanguageComp {
    static contextTypes = {
      language: PropTypes.string
    };

    getLanguage() {
      const language = (this.context && this.context.language) || "ja";
      return T.setTexts(require("./languages/"+language+".json"));
    }
  }
  return Language;
};`
```
How to achieve this using the lib?

**Comment by alexdrel** [comment]
Dynamic file name in require is supported only for nodejs not bundlers like browserify or webpack. Please refer to corresponding documentation about dynamic require.
```setTexts``` method accepts plain JSON object you can load it  from anywhere or you can have one big json with top level dictionary per language and do something like this:  ```T.setTexts(require("./all_languages.json")[language]);```
