### ISSUE TITLE
T.format()

### ISSUE THREAD

**Issue by piyaa** [alexdrel/i18n-react#19]
Can you plz direct me to an example of how does T.format() work. Is it similar to replace the text with other text on fly. ie.:
`T.format(key, "string1", "string2); `

**Comment by alexdrel** [comment]
Please consult [Unit tests](https://github.com/alexdrel/i18n-react/blob/master/tests/basic_test.ts#L90-L107). It's mostly used to expand variables functionality and not to replace text.
P.S. it is not an issue - please use another thread you already opened for further questions.

**Comment by piyaa** [comment]
Got it!! Is there any method that would allow us to replace the text on fly with a new value of text w/o having to store them into json?

**Comment by alexdrel** [comment]
I can't say that I understand the requirement - format does not use the
dictionary (which can come from JSON).
