### ISSUE TITLE
how to handle multiple locales and implicitly current locale?

### ISSUE THREAD

**Issue by timaschew** [alexdrel/i18n-react#2]
I would like to load several locales via `setTexts`. So I need to use the top most context to set which text belongs to which language, right?

It would be nice if I can set the current locale, so that I don't need to pass it every time explicitly.

**Comment by alexdrel** [comment]
You pass to `setTexts(obj)` a regular object, so if you use top-most level for locale - you can just pass the  required sub-tree, e.g. `setTexts(locales['en'])`. I can't recommend using context for locales - it is mostly for optional conditions - like same button may (or may not) have different text depending on which page it is displayed, or numeric context for pluralization. 
Although putting multiple languages on lower-most level is easy to support at first it does not scale as one start to add more and more translations.
