### ISSUE TITLE
Loading the json/yaml files at the root component to be accessible for all its child comps

### ISSUE THREAD

**Issue by piyaa** [alexdrel/i18n-react#20]
Considering that this is my root level comp, I have a language prop set, depending on which I'm rendering the resp language json files.
how can load 2 files: "en" and "ja" depending on the prop language at the top level?
```
import T from "i18n-react";
T.setTexts(require("./languages/"+this.props.language+".json")); //this wont be accessible as the prop has not been set yet

export default class App extends React.Component {
  static propTypes = {
    language: PropTypes.string,
}
  static childContextTypes = {
    language: React.PropTypes.string,
    location: React.PropTypes.object
  };
  getChildContext() {
    return {
      location: this.props.location,
      language: this.props.language
    };
  }
render(){
       <T.p text={{ key: "title"}} />
}
}
```

and the lang prop is set at:
```
export default class Main {
   render(){
        <App
            language="en"
          />
}
}
```
How can I load the files at the root comp for it to be accessible to all its child comps?

**Comment by alexdrel** [comment]
@piyaa, Can I ask you to stop opening new issues about same question. It is a 3rd one in 2 hours. Please use an existing issue when asking for clarifications.
The require is not a magic of the library it is standard node require, the equivalent of ```import```. So import the file  in the root comp and pass the resulting object as prop for example.

**Comment by piyaa** [comment]
As you can see I did the exactly the same , adding the files in the root comp, but my question was how to dynamically handle different languages while importing the json files, your answer does not make any sense as of now

**Comment by alexdrel** [comment]
As I answered in the previous issue the ```require("./languages/"+this.props.language+".json")``` is not good for browsers - it will not work. Please see webpack or browserify documentation for details as it is not related to this library.
And as you can see you can add comments in the closed issue freely, it also can be reopened if needed.

**Comment by piyaa** [comment]
Got it!! On a different nots, Is there any method that would allow us to replace the text on fly with a new value of text w/o having to store them into json?
