### ISSUE TITLE
Ability to render <T> w/o having to write <T.span /> or <T.p /> etc

### ISSUE THREAD

**Issue by piyaa** [alexdrel/i18n-react#22]
Is there a simpler way to be able to call the <T> comp w/o having it wrapped inside an inline element always. I see that its using <T.text ../> for any comp not wrapping inside an element, but is there a way to tweak the code as to use <T../> instead of <T.text../>

```
render() {
    return (
      <Header emptyText="Actions-Section header"   
      </Header>
    );
  }
```
so something like:

```
render() {
    return (
      <Header emptyText={<T text={{key:"section.content"}}/>}   
      </Header>
    );
  }
```

**Comment by piyaa** [comment]
We have components that we usually write:

<App text = "", locale =""/>
where text and locale are the props defined in that comp. My question why cant we implement the same for the <T> comp? why is the necessity for writing the T.text or T.span or T.(anyelement) to render T comp?

**Comment by alexdrel** [comment]
Reason for the change is documented in https://github.com/alexdrel/i18n-react#03 and React requirement to generate DOM node for the component.
