### ISSUE TITLE
Unable to show translation

### ISSUE THREAD

**Issue by sofianegargouri** [alexdrel/i18n-react#23]
Hi guys !

I'm actually trying to integrate i18n-react to my React project, but I've got an issue. When I have a single file Yaml, it works fine, but when I'm adding other lines with tabs, T.translate only shows me the key and not the translation.
Here is my Yaml:
```
accounts:
  login:
    title: 'Log in'
```

And here is my call:
```
I18n.translate("accounts.login.title")
```

With I18n declared as:
```
import T from 'i18n-react';

var locale = (localStorage.getItem('language') == 'fr' || localStorage.getItem('language') == 'en') ? localStorage.getItem('language') : 'en';

T.setTexts(require('../../../assets/locales/' + locale + '.yml'));

export default T
```

**Comment by alexdrel** [comment]
Dynamic file name in ```require``` is not supported by bundlers like browserify or webpack.
