### ISSUE TITLE
Text string having HTML spits HTML as it is instead of parsing

### ISSUE THREAD

**Issue by umakantp** [alexdrel/i18n-react#24]
Hi There,

I have the requirement where some content of the long string has to be bold so my text string is:-

```
T.setTexts({
     'demoBold': 'Hello world, <b>this</b> is really bold.'
});
```

It outputs &lt;b&gt;this&lt;/b&gt; as it is, instead of making it **this** as bold.

I had myself written something similar in my previous project which handles HTML if required, but it was for native JS i18n.js. Haven't yet build one for React js.

Another example could be an anchor tag. I have to currently write it like this.

```
T.setTexts({
     'text1': 'Hello world, ',
     'text2': 'click here',
     'text3': 'for best price ',
});
<T.span text={{key: 'text1'}}> <a href="test.com"><T.span text={{key: 'text2'}}></a> <T.span text={{key: 'text3'}}>
```
and it would output as:-
Hello world, click here for best price.

Above is super bad to write. I know you have T.a for anchor tags, but it still doesn't fix a problem of a string breaking into parts. I would imagine best solution is to allow HTML, something like:-

```
T.setTexts({
     'text1': 'Hello world, <a href="{linkAttr}">click here</a> fir best price'
});
<T.span text={{key: 'text1', linkAttr: 'http://test.com'}}>
```

Ahh simple above. One long string with link stays on translation.

As I mentioned earlier that I had written the similar program for native js for translation. I did something like this (Trying to put in a context of this).

```
T.setTexts({
      'text1': '###SAFE###1. Hello world, we have <b>best</b> price',
      text2: '2. Hello world, we have <b>best</b> price',
});
<T.span text={{key: 'text1'}}>
<T.span text={{key: 'text2'}}>
```

It output as:-

1. Hello world, we have **best** price.
2. Hello world, we have &lt;b&gt;best&lt;/b&gt; price.

Because I have specifically mentioned in text1 that it is safe to print HTML from that translation.

Your thoughts on this?

**Comment by alexdrel** [comment]
@umakantp, thank you for detailed proposal.

Let's start from **bold** and _italic_ - this is absolutely supported now using the markdown syntax:
 ```
T.setTexts({
     'demoBold': 'Hello world, *this* _is_ really bold.'
});
```
Actually it is the most used case for the library - provide friendly way to lightly format the text. I am sure that the MD syntax is much friendlier for translation authors than HTML.

Regarding more complicate case like ```<a>``` - I feel that adding template engine to React is the lost cause by definition, as it will never be powerful enough. The JSX is much better way to do it.

Instead the library supports React components as variables:
```
T.format('Hello world, {link} for the world peace', 
   { link: <T.a href='http://test.com' text='clickHere'/> })
```
So JSX can be incorporated into translation rendering.
