### ISSUE TITLE
Placeholder value does not change depends on the langauage.

### ISSUE THREAD

**Issue by zeegeek** [alexdrel/i18n-react#25]
For example I have an input tag , I dont know how to change the placeholder value. And there is no documentation for that. Little help is much appreciated

<input type="text" name="" id="empName" placeholder="Enter employee number" />.

**Comment by alexdrel** [comment]
```T.translate(...)``` returns plain string that can be placed into an attribute or put to any other use.

**Comment by zeegeek** [comment]
Is it possible to give an example that would be helpful to see .
