### ISSUE TITLE
Problem when switching lang

### ISSUE THREAD

**Issue by remy-poirier** [alexdrel/i18n-react#28]
Hello, 

I am using your library for a while, and I am trying to implement a switch language button, however it seems that some texts (only a few, all others are traduced)

I don't really understand why some texts are traduced and not others.

The thing is that it is nice because the lang changes without the user need to refresh because when user clicks on the lang he wants I simply do 

`let langTranslations = require("../translations/translations-" + response.data  + ".json");
                T.setTexts(langTranslations);`

Then I store the langTranslations var in my Redux state, and it contains all the messages in the good lang, so why some keys are not traduced.

If you have any ideas, I take :)

**Comment by alexdrel** [comment]
Hi, if you have some texts updated but not all of them then my guess is that not all components were re-rendered. Try to ```forceUpdate``` the root component.

**Comment by remy-poirier** [comment]
Hmm yes but it isn't normal because I store the message in the redux reducer, so the props changes when I change the lang and so my component should rerender, and it does because some messages are changing, I really don't understand why some components (always the same) are not rerendering....
