### ISSUE TITLE
Problems with typescript

### ISSUE THREAD

**Issue by giuleon** [alexdrel/i18n-react#29]
Hi,

After the installation I receive the following error:
Could not find a declaration file for module 'i18n-react'.......implicitly has an 'any' type.

In my project I'm using React and typescript 2.3.2.

Regards

**Comment by alexdrel** [comment]
Hi,
I can't reproduce it with my usual test, not even updating everything to the latest version.
I uploaded the test repo to https://github.com/alexdrel/i18n-react-test, please take a look to see what is different.

Thanks
