### ISSUE TITLE
Underline markdown support

### ISSUE THREAD

**Issue by tonoslav** [alexdrel/i18n-react#30]
Can you please add underline tag support into regexes.
I am not sure which char to use as wrapper 
For example double underscore

**Example**
{
text: This is test and \_\_this will be underlined__
}

**Comment by alexdrel** [comment]
Hi @tonoslav ,
I fear that now any change in regexes is a breaking change that must to be an opt-in for backward compatibility. Already the markdown dialect in the library is quite  different from de-facto github standard so I am wary about adding another "invented here" meaning for existing MD syntax.

Let's see if anyone else is interested in underline and what syntax they have in mind.

P.S. I would prefer  ~ underline ~ and ~~ ~strikethrough~ ~~.

**Comment by alexdrel** [comment]
New release: support for ~ underline ~ and ~~ strikethrough ~~  and breaking changes in * bold *. Opt-in for the new syntax with ```MDText(texts, { MDFlavor: 1 })``` .
Enjoy!
