### ISSUE TITLE
Support React 16 render return types

### ISSUE THREAD

**Issue by variousauthors** [alexdrel/i18n-react#32]
As of 16 react supports returning "bare strings" from render functions. That means we no longer need to wrap everything in an army of spans! Would you consider including a translate like,

`<T.something text={'words'}/>`

that would render just the string `"words"`?

https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings

**Comment by variousauthors** [comment]
For the time being I've done the following in my local copy:

<img width="302" alt="screen shot 2017-10-06 at 3 50 23 pm" src="https://user-images.githubusercontent.com/541047/31301370-36b61ab6-aaae-11e7-84cb-bdc842c9161f.png">

**Comment by alexdrel** [comment]
Excellent suggestion. As we all got used to spans I forgot how I tried hard to return plain string from a tag but failed. 
I am thinking ``<T.text/>`` will be perfect as choosing span as default was arbitrary.

**Comment by alexdrel** [comment]
[0.5](https://github.com/alexdrel/i18n-react/releases/tag/release%2F0.5.0) published.
