### ISSUE TITLE
support for lists or dropdowns

### ISSUE THREAD

**Issue by dagda1** [alexdrel/i18n-react#34]
Is there any support for grouping sections of translations for ul.

For example if I have:
```
<ul>
  <li>One</li>
  <li>Two</li>
  <li>Three</li>
</ul>
```
I need to supply individual entries for `One`, `Two`, `Three`
```
<ul>
  <li>T.translate('list.One')</li>
  <li>T.translate('list.Two')</li>
  <li>T.translate('list.Three')</li>
</ul>
```

Is there any saner way I can group text for list, dropdowns etc.

**Comment by alexdrel** [comment]
There is no need to put translate into tags, you can use concise tag syntax (general):
```
<ul>
  <T.text tag="li" text="list.One"/>
  <T.text tag="li" text="list.Two"/>
  <T.text tag="li" text="list.Three"/>
</ul>
```
Or pre-made shortcut for ``li``
```
<ul>
  <T.li text="list.One"/>
  <T.li text="list.Two"/>
  <T.li text="list.Three"/>
</ul>
```

But if you are looking for iterator tag – it is not there, as in React itself. Of course array.map will work.
```
<ul>
  { ['One', 'Two', Three'].map(k=> <T.li key=k text={"list."+k} />)
</ul>
```

P.S. I am closing this item as non-issue for now but please feel free to post here.
