### ISSUE TITLE
No way to test if key exists?

### ISSUE THREAD

**Issue by harry-jones** [alexdrel/i18n-react#36]
Hi

Is there any way to test if a key exists?

I have tried `if(T.translate('myString'))` but this always returns true as the key is returned if a string is missing.

I have strings where I am inserting a variable (example: `if(T.translate(`partners.${partner}.name`))`) so I need to be able to test the string exists before outputting it.

**Comment by alexdrel** [comment]
You found ``notFound`` yet, also note that it could be used as an option in ``translate`` call instead of setting globally.
See [the unit test](https://github.com/alexdrel/i18n-react/blob/master/tests/basic_test.ts#L76-L87).
