### ISSUE TITLE
`notFound` option not working

### ISSUE THREAD

**Issue by harry-jones** [alexdrel/i18n-react#37]
I am configuring the `notFound` option as follows, but it is being ignored and the key is continuing to be returned when a key is not found.

`T.setTexts(require('../../../texts.json'), { notFound: 'myNotFoundString' });`

Is there something wrong with this syntax?

**Comment by alexdrel** [comment]
The 
```
T.setTexts({
..
}, { notFound: 'x' });
``` 
is the correct. And works fine for me in the last versions. I just re-checked - ``x`` is rendered for missing keys.
