### ISSUE TITLE
Document defining translations

### ISSUE THREAD

**Issue by johnwlockwood** [alexdrel/i18n-react#38]
Is there any examples/documentation on defining translations and localizations?

**Comment by alexdrel** [comment]
[Yaml example](https://github.com/alexdrel/i18n-react/tree/master/examples/yaml)

**Comment by johnwlockwood** [comment]
I am looking for something that shows, for example, how to define French version of a key.
greetings
 en: "Hello"
 fr: "Bonjour"

**Comment by alexdrel** [comment]
Usually one has a texts file per language and loads the required one.
