### ISSUE TITLE
symbols screening

### ISSUE THREAD

**Issue by antoniopuero** [alexdrel/i18n-react#4]
is there any hope to have a symbols screening so they are not transformed into an element?
E.g. "some text with two asterisks **"

Would be great to have some kind of "additional symbol" to tell that it should not be interpolated. I believe that back slash doesn't help in this case (/^(|.*?\W)\*(\S.*?)\*(|\W.*)$/.test("text \*\*") === true )

**Comment by alexdrel** [comment]
I am reluctant to enter character screening/back slash business as I feel it is nearly impossible to do with regexes and I do not want to switch to full parsing mode. 
If ** is a rare occasion the simplest workaround is to have a  context var asterisks='**' and render it as {asterisks} which should not cause transformation.

**Comment by antoniopuero** [comment]
ok, got it. thanks
