### ISSUE TITLE
Allow user to provide a function when key not found

### ISSUE THREAD

**Issue by variousauthors** [alexdrel/i18n-react#40]
Hello again :)

We are now hunting for missing keys and translations in out app. We have 5 languages, which we keep in a google sheet (one column per language, and one column for the key). English is the default, because we are English speakers. 

So when looking at the app, if I have

```
<T.text text="Some key"/>
```

and in my google docs `Some key` is missing from the sheet, then I want to see a message like "missing key". Your notFound feature does this (although I would rather see something like `Some key <-- missing!`).

However, when I am looking at Italian, for example, and I see "missing key"... that means _either_ the key is missing the Italian translate _or_ the key is missing entirely. In this case, I would like to see the English if the translation is missing, and "missing key" only if they key is missing from the English locale.

I have accomplished this as follows:

```ts
// in a reducer
import locales, { ILocaleMap } from '../../locales'

function dangerouslySetTexts (locale: ILocaleMap) {
  T.setTexts(locale, {
    notFound: (key: string) => {
      if (locales[LocaleType.EN][key]) {
        return key
      } else {
        return `${key} <-- missing`
      }
    },
    MDFlavor: 0
  })
}
``` 

To do this I augmented your `notFound` property to be a `string | ((key: string) => string)` and have created a function `keyNotFound(notFound, key)` that is called instead of just returning `notFound`.

This is all available for you to inspect in #39 

P.S. part of the problem here is that my team has not been consistent with key names. If all of our keys were like "KEY_NAME" or "key.name" or "ui.key_name" or something, then this would hardly be a problem. As is we just use plain English as key names, because it was convenient.

Never-the-less I think this is a worth-while feature.

**Comment by alexdrel** [comment]
Merged and published in [0.6.3](https://github.com/alexdrel/i18n-react/tree/release/0.6.3).
Thanks
