### ISSUE TITLE
Escape curly braces in text

### ISSUE THREAD

**Issue by NicolasBonduel** [alexdrel/i18n-react#43]
Hello,

I'm trying to find a way to escape the curly braces in my translation files so I can have them in my text.
Using a backslash doesn't seem to work.

Regards.

**Comment by alexdrel** [comment]
Hi,
See [Literal ``](https://github.com/alexdrel/i18n-react#06) syntax for screening.

**Comment by NicolasBonduel** [comment]
Sorry, I missed that, thanks!

**Comment by munkhorgil** [comment]
I have a string that contains bracket but it takes string as array. It supposed to be just a string.
```
`To send your ${ type } press [Enter] and [Shift + Enter] to add a new line ...`
```

**Comment by munkhorgil** [comment]
@alexdrel I just tried your code still same, it takes string as array

**- i18n-react: 0.6.4**

**Comment by alexdrel** [comment]
@munkhorgil  Can you clarify what do you mean by *takes string as array* ?
