### ISSUE TITLE
Is there some way that can get an Object value, not String?

### ISSUE THREAD

**Issue by wanaright10** [alexdrel/i18n-react#44]
something like : 
`{
    key: {
        name: 'Tom'
    }
}`

and I can use T.translate('key') get the object {name: 'Tom'} ?

**Comment by alexdrel** [comment]
``translate`` always returns a string, but as text is just plain JS object you can just read form it:
```
dict=...
T.setTexts(dict)
dict['key'] == { name: 'Tom' }
```
