### ISSUE TITLE
Is there a way to have multiple keys for one translation?

### ISSUE THREAD

**Issue by lhtdesignde** [alexdrel/i18n-react#45]
I have multiple keys that relate to the same translation. This is the yml file:

```
[key_a, key_b]:
translation
```
Seems like the library can't find the keys. Is there another format to get the OR condition working?

**Comment by alexdrel** [comment]
You can't put multiple keys to the same string (as the dictionary is just plain JS object or JSON) but you can reference one key from another:
```yaml
key_a: translation
key_b: {{key_a}}
```

**Comment by lhtdesignde** [comment]
oow cool. ya that's a good idea. Thanks!
