### ISSUE TITLE
[BUG] String contains '.'

### ISSUE THREAD

**Issue by TomPichaud** [alexdrel/i18n-react#46]
Hey, first of all, thanks for your project, I've been using with Gatsby !

My issue is that when a string contains a dot, the translation is not found.

Not working:
`{T.translate('See you soon.')}`
`<T.p text="See you soon." />`
`{T.translate('See you. Soon')}`

Working:
`{T.translate('See you soon')}`

It's easier for me sometimes, to be able to use full sentences or even paragraphs, so in my locales files I've got the default text to translate.

Any help please ?

**Comment by alexdrel** [comment]
Hi @TomPichaud,
Thank you for the detailed and well-researched report. 

But :) it isn't a bug; the texts dictionary was not supposed to be used with literal keys nor to be just string pair list but rather an hierarchical object like the one below:
```javascript
const texts = {
  account: { 
    logoff: {     
      message : "See you soon.",
      //....
    }
  }
}

{T.translate("account.logoff.message")}
```  
As you see dots are used according to the standard JS meaning for accessing object properties.
This is the basic feature of the library from the very first version and it can't be changed.

Also while I admit the simplicity of your solution I can't recommend it. "See you soon." is fine but  how "fall" can be translated w/o a context? 

For the sentence mapping this library is definitely an overkill,  the following single liner will suffice:
```javascript
function translate(t) {
   return texts[t] || t;
}
```

**Comment by TomPichaud** [comment]
Ok, thanks, it's my mistake.
It's much nicer your way anyway!
Thank for your time and explanation.
