### ISSUE TITLE
Please add support for generating inline Hyperlinks

### ISSUE THREAD

**Issue by kriede** [alexdrel/i18n-react#47]
Working around the missing feature of generating links is a mass and in many use cases impossible.
I suggest following the syntax of [markdown](https://daringfireball.net/projects/markdown/syntax#link).

Example:
`This is [an example](http://example.com/ "Title") inline link.`
Result:
This is [an example](http://example.com/ "Title") inline link.

**Comment by alexdrel** [comment]
Hi,
Keeping in mind that the purpose of the library is to help translating react apps and not to make another markdown generator, I feel there is a little value in bare ```<a>``` element. 
Also operational wise the control of links is an application responsibility that should not be delegated to an external file where translations are usually reside.

Using the component composition any however complex component can be incorporated into a translation, like below:
```jsx
  visitLink: "This is {link} inline link.",
  anExample: "an example",

    <T.text text={{  key: "visitLink", 
          link: <a href="//example.com"><T.text text="anExample"/></a> }}/>
```
or using a shortcut:
```
    <T.text text={{ key: "visitLink",
          link: <T.a href="//example.com" text="anExample"/> }}/>
```
Thanks
