### ISSUE TITLE
Config the variable interpolation usage

### ISSUE THREAD

**Issue by samuelcastro** [alexdrel/i18n-react#48]
Is there a way to config how we use variables?

Let's say instead of:
```
"MY_KEY": "My translations {variable}",
```

use like:
```
"MY_KEY": "My translations {{variable}}", // double curly braces
```

**Comment by alexdrel** [comment]
No, it's not configurable. Besides the ``{{...}}`` is reserved for referencing another key. 
But if the only reason is to allow braces in a translations the literal `` syntax can be used:
```
"MY_KEY": "My translations ``{variable}``",
```

**Comment by samuelcastro** [comment]
Ok @alexdrel thanks, the reason is that I'm using a shared dictionary object between 02 projects/frameworks that which already uses double curly braces to define variables, this could be a nice customization feature.
