### ISSUE TITLE
[Question] Work with a simple json syntax

### ISSUE THREAD

**Issue by remy-poirier** [alexdrel/i18n-react#49]
Just a little question, 
I have a project that has grown, and it's very confusing for me to find a key message on a big json file, I would like to be able to do a Ctfr + F to find a key diretcly, and no being forced to watch the entire tree.

What I just is just to have an object like this: 

```
{
    "pageA.title": "Page A title",
    "pageB.title": "Page B Title"
}
```

But it doesn't work, I suppose that it's because when I want to translate `pageA.title`, you try to access the `pageA` object, right ?

Is there any simple solution ?

If not, I have only 2 solutions I think : 

- Map into the new file and recreate object like the old version -_- 
- Refacto the json to replace `.` with `_` or things like that

What do you think about that ?

**Comment by alexdrel** [comment]
> But it doesn't work, I suppose that it's because when I want to translate pageA.title, you try to access the pageA object, right ?

Absolutely right.

If you insist on using dots you can employ something like  [Dot-Object](https://github.com/rhalff/dot-object) or http://jsfiddle.net/remus/tfjH3/ to convert on the fly before passing dictionary to the library.

**Comment by remy-poirier** [comment]
Thank you !
