### ISSUE TITLE
how can I re-render <T />?

### ISSUE THREAD

**Issue by yy8597** [alexdrel/i18n-react#5]
Hi, I like your idea of use .yaml. 👍 

But when I code like this.
```<T className="count" text="count" count={count} />```
It will not re-render automatically.
Because of the props of <T> does not change.

So I edit the js by myself:
![image](https://cloud.githubusercontent.com/assets/2180736/15037452/e381b3c4-12cd-11e6-92bf-c70bca913258.png)
and I miss ```MDText.setTexts = function (t) { MDText.flag = 1; return MDText.texts = t; };```
it work!

or you have a better solution.

**Comment by alexdrel** [comment]
Usually setTexts is called once before any rendering have happened and thus there is no need to re-render. Do you need to dynamically switch texts/languages without re-rendering the whole app?

**Comment by yy8597** [comment]
How do I re-render the whole app?

I use react + redux in my app.
I put the language in component's props. Every <T> will re-render When changing the store.
```
@connect( state => {
    return {
        language: state.common.language
    }
}, {
    ...actions
})
class Component extends React.Component {}
``` 
Is this a bad idea?

**Comment by alexdrel** [comment]
It is not bad - I just assumed that the language is known before rendering starts - the simplest fix is to add language as a prop in T component so once it is changed shouldUpdate will return true.

**Comment by yy8597** [comment]
Yeah...
That's what I did before. 
However, this may seem like a bit of a hassle.
I just put your code in my source code.
Thanks a lot.

**Comment by alexdrel** [comment]
0.2.0 version switched to stateless components which does not have this issue.

**Comment by ahassen** [comment]
How does the new version handle re-rendering when a language is changed?

**Comment by alexdrel** [comment]
The T is stateless in the new version and updates every time when it is being rendered (no shouldComponentUpdate).
