### ISSUE TITLE
console.error when use text in html attributes like label

### ISSUE THREAD

**Issue by Arthuron** [alexdrel/i18n-react#50]
I have a problem with translated text at the inside of a html element attribute.

dictionary: eng.json
```
{
  login:input:email: "E-Mail"
}
```

component: Email
```
import * as React from 'react'
import T from 'i18n-react'
const dictionary = require('./eng')
T.setTexts(dictionary, {MDFlavor: 0})

export default class Email extends React.Component<{}> {
  render() {
    return <Input type="email" label={<T.text text={'login:input:email'}/>}/>
  }
}
```

works very well in a browser, and i see the correct.
But my console and my jest test say that:
```
console.error node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `t`, expected `string`.
```

Same as html attribute **name**.
What can i do to solve my console error?

**Comment by alexdrel** [comment]
``<T.text text={'login:input:email'}/>`` is a React component, not a string and should not be used for html attributes. ``T.translate('login:input:email')`` returns a string.
```js
  render() {
    return <div> 
         <T.text text={'login:input:email'}/>
         <Input type="email" label={T.translate('login:input:email')}/>
     </div>
  }
```
