### ISSUE TITLE
Minified version via NPM package?

### ISSUE THREAD

**Issue by gylaz** [alexdrel/i18n-react#52]
Greetings!

It seems that when this package is installed via NPM, its source isn't minified/compresssed/obfuscated. Is there a way to install a minified version?

**Comment by alexdrel** [comment]
Hi,
The minified version is provided only for the UMD build to be used directly on a web page. The NPM package assume BYOD policy for bundling and minification, which usually works much better when applied on the whole app/bundle level. 
There is no plan to provide minified npm version as ```webpack -p``` will do the job.
