### ISSUE TITLE
Get just the string

### ISSUE THREAD

**Issue by fabioimpe** [alexdrel/i18n-react#55]
Hi,
is there any way just to retrieve the translated string instead of the whole react node?

Thank you

**Comment by alexdrel** [comment]
Hi,

If a translation has *md* formatting the result has to be a react node. For the purpose of testing I use ```ReactDOMServer.renderToStaticMarkup``` to get the HTML string with tags.

**Comment by fabioimpe** [comment]
Hi I understand the point, but how can I provide a translated string to components which requires just a string and not a react node?

**Comment by alexdrel** [comment]
If your translation doesn't have *md* the result will be a string, otherwise there is no way to represent a result as a plain string, so it is logically impossible.

**Comment by fabioimpe** [comment]
Sorry, I'm not understanding, looking at the ts definition file every method returns a React.ReactNode or a React.StatelessComponent... are you referring to the "interpolate" method which returns an "any"?
(just for instance I do not use md in my strings)

**Comment by alexdrel** [comment]
React.ReactNode can be string - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L233-L238

**Comment by fabioimpe** [comment]
Sorry my fault, I was missing this bit, thank you very much for the help :)
