### ISSUE TITLE
non-existing text can be showed as a default value, set as a property

### ISSUE THREAD

**Issue by antoniopuero** [alexdrel/i18n-react#6]
Now, when the text doesn't exist then it's showed as a key. It would be really great if we had a possibility to set "emptyTranslation" property which will be set by default.

I guess in most cases the emptyTranslation will be an empty string, so we could check it in our templates <T text="path.key"/>  ? <T text="path.key"/> : "another defualt text, which is more specific for current component". Now we should check explicilty \<T text="path.key"/\> === "path.key", and in case where "path.key" is the real translation it's not gonna work :)

**Comment by alexdrel** [comment]
@antoniopuero  the use case is not clear for me? Do you have additional checks after rendering <T> or you use```translate()`` directly?

**Comment by antoniopuero** [comment]
The thing is when the translation doesn't exist <T text="key"/> renders "key" instead. I would like it to be configurable, so I could set default value for non-existing translations

**Comment by alexdrel** [comment]
I understood this, but as you said the default most probably will be empty and thus very hard to spot missing translations.

**Comment by antoniopuero** [comment]
Yep, so it's easier to check if the translation exists. `<span>T.translate("key") == "key" ? T.translate("key") : "default text"</span>` - this could cause a problem when key translation in English is key so this condition is broken. So my point is to give an empty string instead. `<span>T.translate("key") || "default text"</span>`

**Comment by alexdrel** [comment]
So it will be useful for explicit call of translate not the T components.
```<span>{T.translate("key") || "default text"}</span> ``` will not work for empty translations which are perfectly OK in many cases (esp with context).

**Comment by antoniopuero** [comment]
seems legit

**Comment by alexdrel** [comment]
New ```notFound``` property in 0.2.0 controls return value for the missing translations.
See [missing keys unit test](https://github.com/alexdrel/i18n-react/blob/69d0139e4782efd84fcc90c403261f1a751899d0/tests/basic_test.ts#L79-91) for the example.

**Comment by antoniopuero** [comment]
wow! you're cool, man

**Comment by antoniopuero** [comment]
hm, but after new release default element is broken
![image](https://cloud.githubusercontent.com/assets/1562509/15208774/1cd33806-1836-11e6-9f1a-1411f305ddda.png)

so I guess it works fine when you specify an element instead of using `<T/>` element. (I'm using es6 module system on babel)

**Comment by antoniopuero** [comment]
oh, I see, this is described in the breaking changes paragraph
