### ISSUE TITLE
Not working when using yml

### ISSUE THREAD

**Issue by ahassen** [alexdrel/i18n-react#7]
I'm trying to use ur pugin for internationalization and I'm following the example on the readme page. If I do `T.setText({refresh: Refresh})` and add the texts to be added there then it works fine. But when I do `T.setText(require('./text.yml'))` then the texs field of `T` is null and I'm not able to access the text.

I've come to the conclusion that its not getting the string from the YAML. Is there another node plugin I need to install to make the require work?

> text.yml

`refresh: 'Refresh'`

**Comment by alexdrel** [comment]
You are right, the example silently assumed webpack and yaml-loader configured. ```setTexts``` accept plain JS object, and YAML loading should be handled by plugin for ```require``` or other means.

**Comment by ahassen** [comment]
I used a JSON file with a JSON loader instead of a YAML for the localization. I don't see a problem with it when using it in the simple example, is there a reason why I should use a YAML instead?

**Comment by alexdrel** [comment]
The only reason is your preferences. Anything that loads JS object is fine.
