### ISSUE TITLE
Unknown prop text on <span> tag when using react 15.2.0

### ISSUE THREAD

**Issue by AlexBeauchemin** [alexdrel/i18n-react#8]
Since react 15.2.0, getting this error:

Warning: Unknown prop `text` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

That's only a warning though, so everything still works

**Comment by alexdrel** [comment]
@AlexBeauchemin , thanks for the report and the pull request. Unfortunately it is not as easy as that. ```text``` is not the only property as even basic example provides arbitrary named variables to be used as substitution strings in the translation. Basically ```T.span``` can have any property and I had relied on React to remove it from the resulting ```span```. 
So not only there are noisy warnings now in 15.2 but it will be properties leaking into DOM in 16.0. This is rather major issue both from security and neatness perspective. 
Right now I do not see a solution that doesn't break backward compatibility with 0.2.

**Comment by AlexBeauchemin** [comment]
At least this PR remove the most frequent 'text' tag so it will remove the warning for most uses. For the other tags, this is on the hand of the user to use valid tags (maybe suggest using data-*, not really pretty but that would keep compatibility)

This topic seems to be discussed a lot in other repos and, from what I understand, most people seems to agree that this is the way to go for now. Looks like this change will be a nightmare for a lot of people though
